println(" ")
println("POTENCIA ACTIVA")
println("P[1] (kW) - Max:  ", maximum(round.(JuMP.value.(P[1,:,:]),sigdigits=3)))
println(" ")
println(round.(JuMP.value.(P[1,:,:]),sigdigits=3))
println(" ")

println(" ")
println("POTENCIA REACTIVA")
println("Q[1] (kVAr) - Max:  ", maximum(round.(JuMP.value.(Q[1,:,:]),sigdigits=3)))
println(" ")
println(round.(JuMP.value.(Q[1,:,:]),sigdigits=3))
println(" ")

println("Vmin (V): ", minimum(round.(sqrt.(JuMP.value.(v))/VB, sigdigits=3)))
println(" ")
println("I[1] (A): ", round.(sqrt.(U[1,:,:]), sigdigits=3))
println(" ")

println("=============================================================")
println("LINEAS:", Int.(JuMP.value.(capacity_L)))
println(" ")
println("TRANSFORMADOR:", Int.(value.(xtr).*lista_TR))
println(" ")

println("=============================================================")
println(" ")
println("OLTC: ")
println(sqrt.(JuMP.value.(Vb))/VB)
println(" ")

println(" ")
println("SVC: ", Int.(JuMP.value.(xsvc) .* lista_SVC'))
println(" ")
println("CB: ", Int.((JuMP.value.(sum.(xcb[i,:] for i in I)))))
println(" ")
println("=============================================================")